name: prediksi_kebakaran
services:
  streamlit:
    build: docker/streamlit
    image: hendrikt/ml_process_streamlit
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8500:8500
    volumes:
      - ./:/home/
  api:
    build: docker/api
    image: hendrikt/ml_process_api
    container_name: api_backend
    ports:
      - 8080:8080
    volumes:
      - ./:/home/