# path
data_raw: data/raw/smoke.csv
data_final: data/processed/ori_new.pkl
path_train:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
path_valid:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
path_test:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
path_train_feat:
- data/processed/x_train_feat.pkl
- data/processed/y_train_feat.pkl
path_valid_feat:
- data/processed/x_valid_feat.pkl
- data/processed/y_valid_feat.pkl
path_test_feat:
- data/processed/x_test_feat.pkl
- data/processed/y_test_feat.pkl
final_model_path: models/production_model.pkl
training_log_path: log/training_log.json

# Nama Kolom
new_cols:
- utc
- temperature
- humidity
- tvoc
- eco2
- raw_h2
- raw_ethanol
- pressure
- pm10
- pm25
- nc05
- nc10
- nc25
- cnt
- fire_alarm




# tipe data
datetime_columns:
- utc
float_columns:
- temperature
- humidity
- pressure
- pm10
- pm25
- nc05
- nc10
- nc25
int_columns:
- tvoc
- eco2
- raw_h2
- raw_ethanol
- cnt
- fire_alarm

# Predictors and target
target: fire_alarm
predictors:
- temperature
- humidity
- tvoc
- eco2
- raw_h2
- raw_ethanol
- pressure
- pm10

# Ratio Split
test_size: 0.3
valid_size: 0.5